# This workflow builds the docs and deploys them to GitHub Pages on every commit to the master branch
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy Docs

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install --frozen-lockfile
    - uses: sterlingwes/gh-pages-deploy-action@v1.1
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        source-directory: docs
        build-command: yarn doc
